// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMModel;

#nullable disable

namespace UMModel.Migrations
{
    [DbContext(typeof(UMContext))]
    [Migration("20260223124623_AddConfigs")]
    partial class AddConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMModel.Models.Card", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string[]>("AllowedFighters")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int?>("Boost")
                        .HasColumnType("integer");

                    b.Property<string>("IncludedInDeckWithSidekick")
                        .HasColumnType("text");

                    b.Property<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LoadoutName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("LoadoutName");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("UMModel.Models.ContentUpdate", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("CreatedDT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ContentUpdates");
                });

            modelBuilder.Entity("UMModel.Models.CoreScript", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CoreScripts");
                });

            modelBuilder.Entity("UMModel.Models.Fighter", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("CanMoveOverOpposing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHero")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmall")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadoutName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MeleeRange")
                        .HasColumnType("integer");

                    b.Property<int>("Movement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartingHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("LoadoutName");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("UMModel.Models.Loadout", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<string>>("CantBePlayedWith")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("ChoosesSidekick")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumHandSize")
                        .HasColumnType("integer");

                    b.Property<int?>("StartingHandSize")
                        .HasColumnType("integer");

                    b.Property<List<string>>("StartsWithCards")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("StartsWithSidekicks")
                        .HasColumnType("boolean");

                    b.HasKey("Name");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("UMModel.Models.MatchConfig", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int>("ActionsPerTurn")
                        .HasColumnType("integer");

                    b.Property<int>("ExhaustDamage")
                        .HasColumnType("integer");

                    b.Property<int>("FirstPlayerIdx")
                        .HasColumnType("integer");

                    b.Property<int>("InitialHandSize")
                        .HasColumnType("integer");

                    b.Property<int>("ManoeuvreDrawAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHandSize")
                        .HasColumnType("integer");

                    b.Property<bool>("RandomFirstPlayer")
                        .HasColumnType("boolean");

                    b.Property<bool>("RandomMatch")
                        .HasColumnType("boolean");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            ActionsPerTurn = 2,
                            ExhaustDamage = 2,
                            FirstPlayerIdx = -1,
                            InitialHandSize = 5,
                            ManoeuvreDrawAmount = 1,
                            MaxHandSize = 7,
                            RandomFirstPlayer = true,
                            RandomMatch = true,
                            Seed = 0,
                            TeamSize = 1
                        });
                });

            modelBuilder.Entity("UMModel.Models.Card", b =>
                {
                    b.HasOne("UMModel.Models.Loadout", "Loadout")
                        .WithMany("Deck")
                        .HasForeignKey("LoadoutName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("UMModel.Models.Fighter", b =>
                {
                    b.HasOne("UMModel.Models.Loadout", "Loadout")
                        .WithMany("Fighters")
                        .HasForeignKey("LoadoutName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("UMModel.Models.Loadout", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("Fighters");
                });
#pragma warning restore 612, 618
        }
    }
}
